displayName: JWT Middleware
type: middleware
import: github.com/numaga94/traefik-jwt-middleware
summary: 'Verify JWT Token in auth header'

testData:
  encodedHeader:
    - 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ._XEngvIuxOcA-j7y_upRUbXli4DLToNf7HxH1XNmxSc'
